### DISCUSSION TITLE
What code positions text tracks above control bar?

### DISCUSSION THREAD

**Discussion by jrochkind** [videojs/video.js#9050] [Q&A]
I am writing a custom local theme that makes the control bar *taller* (higher) than usual. 

There is definitely already code in video.js that positions text tracks (subtitles, captions) *above* the control bar when it is visible. You can see the text track jump up when control bar is visible, and then be lower again when it is not. 

However, it's not jumping high enough for my CSS themed higher control bar -- it's still jumping up above the height of the "standard" control bar, so winding up part-way underneath my themed higher control bar. 

I am looking for the code that positions the subtitles, so I can figure out how it is deciding how high to position them, and see how to intervene to change the calculation or make it so it's correct for my theme. But I can't find where this happens!

i can see that a container div for subtitles with class `vjs-text-track-cue` ends up with an inline `style` attribute, including an `inset` attribute, that is what positions it to be above the control bar, when it is visible.  But I can't find what code actually calculates or sets this value.  It seems like it must be something that gets called as part of [TextTrackDisplay#updateDisplay](https://github.com/videojs/video.js/blob/09eb7150453bb2cbd96e638be3e115590ae98578/src/js/tracks/text-track-display.js#L276) -- as that's what is called to position the text track, see for instance #9023 which calls it more often to get the text track properly moved when the control bar appears due to user activity. 

But I put a breakpoint there and step through that method, and i just can't find any code that is doing this!   

Does anyone know where the code that calculates this `insert` value for `.vjs-text-track-cue` container is, so I can look at it? Or have any other advice for getitng text track to be positioned properly when writing a theme that makes the control bar have a larger height than default?

**Comment by phloxic** [comment]
This seems to work for me[tm] (values according to taste):

```scss
.video-js {
  .vjs-text-track-display {
    bottom: 7em;
  }

  &.vjs-user-inactive.vjs-playing .vjs-text-track-display {
    bottom: 3.5em;
  }

  &.vjs-user-inactive.vjs-paused .vjs-text-track-display {
    bottom: 7em;
  }
}
```
It has no effect in fullscreen mode though.

**Reply by jrochkind** [reply]
Thank you! 

That does seem to basically work in general case anyway.  And I think I see the default CSS that does this but for 3em, the default size of the control bar? Although with slightly different/simpler CSS:

https://github.com/videojs/video.js/blob/09eb7150453bb2cbd96e638be3e115590ae98578/src/css/components/_text-track.scss#L2-L20

It still feels like video.js might be doing something else by default too -- or else why was #9023 necessary to fix that edge case? (Which I confirm it was and did!).  Still curious if anyone else has any more info on this, what might be going on in JS. 

But the CSS does seem to work, at least in cases I can think of to test -- hopefully no edge cases waiting to be discovered. 

Based on finding the original CSS, it seems like this simplification is actually sufficient?  

```css
// set to greater height of our new custom control bar, default
// built-in videoJS css will already lower it when control bar is not present
.vjs-text-track-display {
  bottom: 4.5em; 
}
```

There is something odd going on where the font-size of the text track is SMALLER when control bar is present than when not. But this happens in default stock videojs too, so is an existing issue -- or is maybe as expected, if the font size is calculated based on available space above control bar?  

In my player, the font-size is set in an inline style attribute on `.vjs-text-track-cue` to `16.16px` without control bar showing, and `15.16px` when (standard default) control bar with default css is showing. But with higher `bottom` to clear larger control bar, `14.41px` with standard defacontrol bar showing, making the difference in font size even more apparent. Hm, wonder if this is a bug to be filed? 

Thanks for any additional input!

**Reply by jrochkind** [reply]
OK here's another version of CSS, based on original video.js CSS and a translateY idea from my colleagues working on https://github.com/samvera-labs/ramp/pull/665, that does not make font-size difference _worse_, it just remains the same as in default videoJS... where I'm curious if it is considered a bug or not?

```css
// 1.5 em is differnece in size of our custom control bar (4.5) em, and default videojs control bar (3em), negative.
// Move tracks out of way of control bar. Class below will reset it to not be out of the way when control bar is not
// visible, using same technique as default video.js. 
// See https://github.com/videojs/video.js/discussions/9050 and https://github.com/videojs/video.js/blob/09eb7150453bb2cbd96e638be3e115590ae98578/src/css/components/_text-track.scss#L2-L20

.vjs-text-track-display {
  transform: translateY(-1.5em);
}

// Move captions down when controls aren't being shown
.video-js.vjs-controls-disabled .vjs-text-track-display,
.video-js.vjs-user-inactive.vjs-playing .vjs-text-track-display {
  transform: translateY(0);
}
```

**Comment by phloxic** [comment]
@jrochkind - I like the translateY approach, thanks.

**Reply by jrochkind** [reply]
Huh, as I continue testing, it seems that this may not work in Safari?  Anyway work in progress. :(

**Reply by jrochkind** [reply]
oh boy, and it also, in all browsers that show it, messes up other things that wind up with .text-track-display, like the text track settings panel. 

OK, yeah, this stuff is hard, to find something wihtout edge cases.

**Reply by jrochkind** [reply]
@phloxic broken in safari for captions that take two lines on screen. Your version originally doesn't work in safari for captions that take up two lines on screen either, to me!

Would you want to test and tell me if you can reproduce?  I hope I'm not just getting confused. 

The original default video.js _does_ successfully move two-line captions above (originaly sized) control bar.  Still wish I could figure out how it was doing that!

**Reply by jrochkind** [reply]
oh wait, maybe this is because safari is using native captions, and the styles aren't effecting them at all.... :(

**Reply by phloxic** [reply]
@jrochkind, setting `html5: { nativeTextTracks: false }` should do it for Safari - unless you need native subtitles, e.g. if you deliver them via HLS.

**Reply by jrochkind** [reply]
OK. It's possible the safari bug with multi-line subtitles and native subtitles exists even in default video.js? Not totally sure. This is so confusing.  How are safari native subtitles managing ot reposition above the default size video.js controlbar by default, still curious!

So, here's another workaround using safari custom selectors for native subtitles, that seems to work for me even with native subtitles now... not totally sure I understand why or why these values I feel a bit cargo-culty, but I seem to have a solution. 

Sorry, in SASS since that's what I'm using and I don't want to accidentally typo when trying to convert, confusing enough already.   Here's my whole solution, tested in multiple browsers/platforms via browserstack.com, seems to be good enough. 

```sass
.video-js.vjs-my-custom-theme {
  // Fix subtitles for control bar

  // 2.5 em is differnece in size of our custom control bar (4em + 1 em padding == 5em, plus 0.5em progress controls == 5.5em?), and
  // default videojs control bar (3em), negative. - 2.5em.
  //
  // Moves text tracks out of way of control bar. Class below will reset it to not be out of the way when control bar is not
  // visible, using same technique as default video.js.
  // See https://github.com/videojs/video.js/discussions/9050 and
  //    https://github.com/videojs/video.js/blob/09eb7150453bb2cbd96e638be3e115590ae98578/src/css/components/_text-track.scss#L2-L20

  .vjs-text-track-display {
    transform: translateY(-2.5em);
  }

  // Move captions down when controls aren't being shown
  &.vjs-controls-disabled .vjs-text-track-display,
  &.vjs-user-inactive.vjs-playing .vjs-text-track-display {
    transform: translateY(0);
  }

  // Okay, now hit some Safari-only classes for native text tracks...
  // possibly this is required for two-line text tracks, not sure
  // if that bug exists also in default video.js, not sure why 1.75em
  // seems right, 0.75em less than above.
  video::-webkit-media-text-track-container {
    transform: translateY(-1.75em);
  }
  &.vjs-controls-disabled, &.vjs-user-inactive.vjs-playing {
    video::-webkit-media-text-track-container {
      transform: translateY(0);
    }
  }

}

**Comment by jrochkind** [comment]
Copying from thread to mark as my own current answer....   also handling some safari weirndess with multi-line subtitles and native subtitles exists even in default video.js? Not totally sure. This is so confusing. How are safari native subtitles managing to reposition above the default size video.js controlbar by default, still curious! 

I think the default video.js controlbar is too small for many modern uses, and it would be great to to have a supported not-have-to-reinvent-the-wheel approaching to a theme with a taller control bar!

Here is my current solution, including workaround using safari custom selectors for native subtitles, that seems to work for me even with native subtitles now... not totally sure I understand why or why these values I feel a bit cargo-culty, but I seem to have a solution.

video.js default out of the box makes subtitles SMALLER when controlbar appears -- which I think could be considered undesirable out of the box? The translateY approach here for larger controlbar at least keeps from making that _worse_, the subtitle size with controlbar remains same as defualt -- other  approaches made it _even smaller_ in a very noticeable/hard to read way. 

Sorry, in SASS since that's what I'm using and I don't want to accidentally typo when trying to convert, confusing enough already. Here's my whole solution, tested in multiple browsers/platforms via browserstack.com, seems to be good enough.

```sass
.video-js.vjs-my-custom-theme {
  // Fix subtitles for control bar

  // 2.5 em is differnece in size of our custom control bar (4em + 1 em padding == 5em, plus 0.5em progress controls == 5.5em?), and
  // default videojs control bar (3em), negative. - 2.5em.
  //
  // Moves text tracks out of way of control bar. Class below will reset it to not be out of the way when control bar is not
  // visible, using same technique as default video.js.
  // See https://github.com/videojs/video.js/discussions/9050 and
  //    https://github.com/videojs/video.js/blob/09eb7150453bb2cbd96e638be3e115590ae98578/src/css/components/_text-track.scss#L2-L20

  .vjs-text-track-display {
    transform: translateY(-2.5em);
  }

  // Move captions down when controls aren't being shown
  &.vjs-controls-disabled .vjs-text-track-display,
  &.vjs-user-inactive.vjs-playing .vjs-text-track-display {
    transform: translateY(0);
  }

  // Okay, now hit some Safari-only classes for native text tracks...
  // possibly this is required for two-line text tracks, not sure
  // if that bug exists also in default video.js, not sure why 1.75em
  // seems right, 0.75em less than above.
  video::-webkit-media-text-track-container {
    transform: translateY(-1.75em);
  }
  &.vjs-controls-disabled, &.vjs-user-inactive.vjs-playing {
    video::-webkit-media-text-track-container {
      transform: translateY(0);
    }
  }

}
```

**Reply by jrochkind** [reply]
Ooh, I realized adding a `transition: transform 0.25s ease-in-out;` to both classes makes this even nicer (and more like youtube's implementation of captions moving for control bar).

**Reply by phloxic** [reply]
@jrochkind, good idea. I'll probably go for
```scss
.video-js.vjs-custom {
  .vjs-text-track-display {
    transform: translateY(-5em);
    transition: transform 0.2s ease-out;
  }

  &.vjs-controls-disabled .vjs-text-track-display,
  &.vjs-user-inactive.vjs-playing .vjs-text-track-display {
    transform: translateY(-1.5em);
    transition: transform 0.5s ease-in;
  }
}
```
As for Safari native, good to know, haven't tried it yet.
