### ISSUE TITLE
controls not showing in any of the browsers

### ISSUE THREAD

**Issue by zahidaoui** [videojs/video.js#1141]
Here is my HTML code:

``` html
<div id="video">
<div id="btn"></div>
<video id="my_video_1" class="video-js vjs-default-skin" 
 preload="auto" width="470" height="251" poster="<? bloginfo('stylesheet_directory'); ?>/images/video.gif" onclick="this.play();" controls
 data-setup="{}">
 <source src="<? bloginfo('stylesheet_directory'); ?>/video/final.webm" type='video/webm'/>
 <source src="<? bloginfo('stylesheet_directory'); ?>/video/final.mp4" type='video/mp4'/>
</video>
```

and CSS:

``` css
video {
    padding-left:15px;
    padding-top: 21px;  
}

#video{
    margin-top:70px;
    background: url(images/vector.png) no-repeat;
    background-size: cover;
    width:502px;
    height:286px;
    text-align: left;
    position:relative;
}
```

When I click on the poster, the video plays, but the controls don't appear, and I have got this problem with chrome, firefox and safari. Any solution? Thanks

Edit by @mmcc: syntax
