### ISSUE TITLE
Self-hosting instructions don't mention font/ folder.

### ISSUE THREAD

**Issue by pcj** [videojs/video.js#1596]
I just installed video.js on my site.  Initially, the video player would show but only squares would appear for all the controls. 

![screen shot 2014-10-17 at 3 21 21 pm](https://cloud.githubusercontent.com/assets/50580/4686289/c893b35c-5643-11e4-98cc-26e6b793b951.png)

These controls glyphs are content attributes of the :before pseudo-elements which reference the font files as specified in the video-js.css file.  According to the getting started instructions, all I needed to do was include the video.js and video-js.css files in my site, nothing was mentioned about the font/ files.

```shell
pcj:~/github.com/video.js/dist/video-js*master$ cp font/vjs.* ~/www/fonts/
```

To get it working, I copied the font/vjs.* files my font directory and adjusted the paths in the css file.

```css
/* Custom Icon Font
--------------------------------------------------------------------------------
The control icons are from a custom font. Each icon corresponds to a character
(e.g. "\e001"). Font icons allow for easy scaling and coloring of icons.
*/
@font-face {
  font-family: 'VideoJS';
  src: url('/fonts/vjs.eot');
  src: url('/fonts/vjs.eot?#iefix') format('embedded-opentype'), url('/fonts/vjs.woff') format('woff'), url('/fonts/vjs.ttf') format('truetype'), url('/fonts/vjs.svg#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

![screen shot 2014-10-17 at 3 22 02 pm](https://cloud.githubusercontent.com/assets/50580/4686291/d1062cea-5643-11e4-9549-c5f9e4becf26.png)

Given the popularity of this library, I'm guessing I missed something obvious.  No?
