### ISSUE TITLE
poster image is not being removed after video playback begins

### ISSUE THREAD

**Issue by propertunist** [videojs/video.js#1790]
i am testing the latest released version of video.js here in firefox 34 - linux...
i have configured the player to play back with a poster image and for a while this worked fine. now though, when i play video on my site, the poster image does not get removed/hidden after i press play.
when i examine the poster image via the browser inspector i do not see any unusual css (such as maybe an !important tag for the background-image value of the poster).

anyone know why this may be?

n.b. this problem is not occurring when i play back the demo video on the video.js website.

**Comment by Gappa** [comment]
Are you using a CSS file generated by the Designer (http://designer.videojs.com)?

Because the file generated is missing this cruical piece of code:
```css
/* Hide the poster after the video has started playing */
.video-js.vjs-has-started .vjs-poster {
  display: none;
}
```
But look for this code anyway :)

I don't know what other CSS is missing, but adding this works.
