### ISSUE TITLE
responsive subtitle

### ISSUE THREAD

**Issue by ErixEnet** [videojs/video.js#2161]
I have a problem with responsive subtitle
if the player full screen becomes very small subtitle

normal
![aa2](https://cloud.githubusercontent.com/assets/11387546/7670823/8fcc6ebe-fcde-11e4-9a3e-e242182c814e.png)

full screen
![2](https://cloud.githubusercontent.com/assets/11387546/7670811/356833fe-fcde-11e4-8197-
be0c7965ee7a.jpg)

my site http://nontonfilm.id/movie/despicable-me-2/

**Comment by gregory0219998** [comment]
What code did you put?

**Comment by mmcc** [comment]
If you'd like the font size to grow more after going fullscreen, you can add a quick CSS rule: 

```css
.video-js.vjs-fullscreen .vjs-subtitles {
  font-size: 350% !important; // default is 250%
}
```
