### ISSUE TITLE
Add text to play button

### ISSUE THREAD

**Issue by thehung2224** [videojs/video.js#2431]
I want to add text to play button instead icon. How can I archive that?

``<div class="vjs-big-play-button" role="button" aria-live="polite" tabindex="0" aria-label="play video"><span aria-hidden="true"></span></div>``

This is code when I inspected. Thanks in advance.

**Comment by thehung2224** [comment]
Could anyone help me?

**Comment by mmcc** [comment]
You could do this with CSS if you wanted. 

```css
.vjs-default-skin .vjs-big-play-button:before {
  font-family: inherit;
  content: 'play';
}
```

Here's a [working example](http://jsbin.com/meremi/edit?html,output)
