### ISSUE TITLE
Finalize default control bar components (and their options)

### ISSUE THREAD

**Issue by heff** [videojs/video.js#2507]
- Do we show current time in the bar or just on hover
- Vertical/horizontal (inline) volume
- Spinner icon (because Steve doesn't like that it's Picasa)

Followup
- Do we remove the other (hidden) volume components from the codebase

**Comment by heff** [comment]
@mmcc, @gkatsev, @dmlap, I agree with the following statements. Please give me an agree/disagree for each.

- The controls that are currently shown by default are good and are in the best order
- We should continue to show just the remaining time, with the current time on hover
- We should remove the independent volume and mute controls from the control bar and rely on just the volume menu, which we've made work with at least the two primary volume designs

Default player controls:
![screen shot 2015-09-02 at 3 20 07 pm](https://cloud.githubusercontent.com/assets/166/9646192/23bc0124-5186-11e5-94d6-088760420462.png)

With hover states on:
![screen shot 2015-09-02 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/166/9646256/c78bd1d0-5186-11e5-9880-79be5c8fbafd.png)

What the player looks like with all control bar components 'turned on'

![screen shot 2015-09-02 at 2 49 00 pm](https://cloud.githubusercontent.com/assets/166/9645645/d99d36d4-5181-11e5-89d0-be43e12cf474.png)

### Notes
- The volume slider needs to be fixed if we keep it, hoping we don't.
- The live control won't ever show now and needs the css to show it added back

And FYI, here's the CSS that was needed to show the ones that aren't showing by default. This uses the minimum strength of selectors required to show the control, in case we want the optional controls any easier to show. I expect to get requests on how to show the other time controls, to match the old way.

```css
    /* Hidden by default, selectively shown. 
       At this point this is how a skin designer would show them. */
    .video-js .vjs-current-time { display: block; }
    .video-js .vjs-time-divider { display: block; }
    .video-js .vjs-duration { display: block; }
    .video-js .vjs-mute-control { display: block; }
    .video-js .vjs-volume-control { display: block; }

    /* Could be broken. Can't find what's supposed to show it now */
    .video-js .vjs-live-control { display: block; }

    /* Programmatically hidden with vjs-hidden when no tracks */
    .video-js .vjs-chapters-button { display: block !important; }
    .video-js .vjs-subtitles-button { display: block !important; }
    .video-js .vjs-captions-button { display: block !important; }

    /* Hidden with state classes */
    .video-js .vjs-control-bar { display: flex; }
    .video-js.vjs-has-started .vjs-big-play-button { display: block; }
```
