### ISSUE TITLE
Fullscreen button

### ISSUE THREAD

**Issue by Tralapo** [videojs/video.js#2688]
I stream a livestream without sound and without DVR, so I hide all the video.js controls, except for the play/pause button and the full screen button. I think that looks more clean.

In 4.x, the full screen button was always on the right, no matter which buttons you hid. Now, in video.js 5, the full screen button goes to the left, directly next to the play/pause button, if you disable the other components.

I can, off course, hack some CSS to push it back to the right (I think people expect to find it over there), but I was curious if this was a choice made with the development of video.js v5, or if it's a bug.

![videojs](https://cloud.githubusercontent.com/assets/11296429/10368845/9a63c498-6dd7-11e5-98f3-100a2a6a99cb.jpg)

**Comment by mmcc** [comment]
This was definitely a choice. The reason it worked before was that we were using floats before which broke tab order. Now we use a Flexbox layout, which is *much* better suited for layouts like this.

You can do something like this:

```scss
.my-custom-skin {
  .vjs-volume-menu-button,
  .vjs-progress-control,
  .vjs-remaining-time {
    display: none;
  }
  
  // Anything that supports Flexbox
  .vjs-custom-control-spacer {
    display: flex;
    flex: auto;
  }
  
  // IE8
  &.vjs-no-flex .vjs-custom-control-spacer {
    width: auto;
  }
}
```

[Example](http://jsbin.com/dinafizuyu/edit?html,css,output)

**Comment by Tralapo** [comment]
Thanks for the explanation. I see your example is working on JS Bin, but it won't work if I copy/past it as regular CSS? Why is that?

**Comment by mmcc** [comment]
Sorry, that example is SCSS. That translates to something like this:

```css
.my-custom-skin .vjs-volume-menu-button,
.my-custom-skin .vjs-progress-control,
.my-custom-skin .vjs-remaining-time {
  display: none;
}
.my-custom-skin .vjs-custom-control-spacer {
  display: flex;
  flex: auto;
}
.my-custom-skin.vjs-no-flex .vjs-custom-control-spacer {
  width: auto;
}
```
