### ISSUE TITLE
Default theme issue with border-box

### ISSUE THREAD

**Issue by jordanthomas** [videojs/video.js#271]
The default theme has an odd line through the controlbar when the document is set to box-sizing: border-box.

I was able to fix it by adding the follow css:

``` css
.video-js * {
    -moz-box-sizing: content-box;
    -webkit-box-sizing: content-box;
    box-sizing: content-box;
}
```
