### ISSUE TITLE
Progress bar hover bug

### ISSUE THREAD

**Issue by kokororin** [videojs/video.js#2964]
When there is a 'word-break:all' in my style, the progress bar hover will also work breaked.
like this:
![3d6024a0-c141-476f-b9d0-fec1bcf1d039](https://cloud.githubusercontent.com/assets/10093992/12078397/9b87d6da-b24b-11e5-914a-5400459719a6.png)
To solve the problem,I added `word-break: normal!important;`in `video-js.css`
code like this:

``` css
.video-js .vjs-big-play-button:before, .video-js .vjs-control:before, .video-js .vjs-modal-dialog, .vjs-modal-dialog .vjs-modal-dialog-content {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  word-break: normal!important; }
```
