### ISSUE TITLE
Time Divider Div Not Responsive to Vertical CSS

### ISSUE THREAD

**Issue by tneaves** [videojs/video.js#2969]
The most relevant piece for your attention is the `.vjs-time-divider` -- no matter what selector I use, I seem unable to move the `div`, `span`, etc. This seems like a bug. 

```css
....
.video-js .vjs-time-control.vjs-time-divider div  {
     bottom: 50% !important;
}
```

The effect, for instance, when moving other components, means that the divider is left behind.

![image](https://cloud.githubusercontent.com/assets/14412556/12121465/71f62aac-b3a3-11e5-9c85-3a9fc1fefdc0.png)
