### ISSUE TITLE
video-js.css corrupt

### ISSUE THREAD

**Issue by arcontact** [videojs/video.js#3013]
I found several errors in http://vjs.zencdn.net/5.4.6/video-js.css:
`content: "";`
`@media �screen`
Maybe its related to character encoding?
Can you provide me minified CSS with UTF-8 encoding?

**Comment by gkatsev** [comment]
None of those are errors and that file is fully utf-8 compliant. The issue is that sass converts the unicode codepoints into utf8 characters but when you view the css directly, it looks like a square because you don't have the font loaded in. We do have a fix in a prerelease version of videojs that will go around sass and have the final output of the css have the codepoints in them directly.
As for the `@media` clause, apparently, it's a trick to keep IE8 inline: https://github.com/videojs/video.js/blob/master/src/css/components/_control-bar.scss#L45-L52
Thanks, hope that helps clear things up.

**Comment by arcontact** [comment]
Thank you very much i really appreciate your work.

**Comment by thomaspeeters** [comment]
`@media �screen` is causing unexpected behaviour in IE11 on Windows 7 for me. It is supposed to be `@media \0screen`, [which should target only IE8](http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/), but it appears to be broken.

Currently, the rule is applied in IE8 and higher, instead of just IE8. Changing the `�` to `\0` in the CSS fixed the issue for me.

The expected behaviour is for the @media rule to not be applied in IE11, but the actual behaviour is that it is applied.
Perhaps it would be better to separate IE8-specific CSS in the same way IE8-specific JS is in a separate file?

For clarity's sake I should add where I encountered this bug. I am overriding the default CSS so the controls aren't hidden during playback when the player is inactive.

These are my overriding rules:
```CSS
.video-js .vjs-control-bar {
    display: flex;
}

.vjs-has-started.vjs-user-inactive.vjs-playing .vjs-control-bar {
    visibility: visible;
    opacity: 1;
}
```

In Chrome and Firefox this results in a controlbar which is always visible, in IE11 this results in all the button icons disappearing when the player enters the `inactive` state.
Adding the following overriding rule **did not** work, for a reason unknown to me.

```CSS
@media screen {
    .vjs-user-inactive.vjs-playing .vjs-control-bar :before {
        content: inherit; }
}
```
