### ISSUE TITLE
Caption track labels are always lowercase

### ISSUE THREAD

**Issue by thomaspeeters** [videojs/video.js#3015]
Because the caption menu is wrapped in a `div` with the `.vjs-menu` class, all caption labels have the `text-transform: lowercase;` rule applied to them.

I can fix this with some custom CSS like this:

```CSS
.vjs-captions-button .vjs-menu li
{
    text-transform: none;
}
```

However, I feel a cleaner solution should be possible, this shouldn't be the default behaviour for caption labels.

**Comment by gkatsev** [comment]
I think we're going to call this a stylistic choice. Plus, it should be fairly easy to fix this.
```css
.vjs-menu li {
  text-transform: initial;
}
```
