### ISSUE TITLE
16:9 or 4:3 scaling option - videos of a different aspect ratio aren't vertically centred

### ISSUE THREAD

**Issue by andfinally** [videojs/video.js#3027]
V5 of VideoJS added vjs-16-9 or vjs-4-3 CSS classes you can apply to the video element, which size it responsively to one of those aspect ratios. This works nicely, apart from when the video in the player has a different aspect ratio. In that case, the video is aligned at the top of the player with a black strip below.

![16-9 video player](https://cloud.githubusercontent.com/assets/1647564/12536183/1cea594c-c295-11e5-89ee-bb42bae90691.png)

There's a small adjustment you can make to the CSS that'll display these videos with normal letterboxing instead. In _layout.scss change

``` scss
.video-js .vjs-tech {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

to

``` scss
.video-js .vjs-tech {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    margin: auto;
}
```

This should vertically centre videos within the player.

![letterboxing](https://cloud.githubusercontent.com/assets/1647564/12536192/bcc8b8d2-c295-11e5-9984-8ad8f27ac08f.png)

I'm unable to get the SCSS build working on a local copy of the VideoJS code, so posting this as an issue.
