### ISSUE TITLE
CSS of volume

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#3029]
Hi guys. Yhis is how is rendered the volume in your homepage. Volume css works great. there are no error.

<img src='http://s28.postimg.org/7ae6j768d/videojs1.jpg' border='0' alt="videojs1" /></a>

Anyway, if I try to use a custom code, this is what I see

<img src='http://s7.postimg.org/9xw3l9hi3/videojs2.jpg' border='0' alt="videojs2" /></a>

As you can see, the volume bar is white everytime. 
Please try to open this and make a test: http://codepen.io/heff/pen/EarCt
That are the default option, I didn't changed anything.
What can I do for fix this?

**Comment by gkatsev** [comment]
Looks like the issue is with this piece of css on line 101:
```css
/* The slider bar color is used for the progress bar and the volume bar
   (the first two can be removed after a fix that's coming) */
.video-js .vjs-volume-level,
.video-js .vjs-play-progress,
.video-js .vjs-slider-bar {
  background: $primary-foreground-color;
}
```
Specifically because `.video-js .vjs-slider-bar` selector is there.
