### ISSUE TITLE
Very unspecific css selector

### ISSUE THREAD

**Issue by vxsx** [videojs/video.js#3492]
## Description
Using default skin affects the styles of the website not related to video js
Reduced test case http://jsbin.com/liwetupuke/edit?html,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Add provided css
2. All your `legend` elements now have width of 100px

### Expected
Videojs css doesn't affect website styles

### Actual
It does

### Additional information
The bug is coming from here https://github.com/videojs/video.js/blob/238c752aee45cd6b2b69585d740c3991796ca3b1/src/css/components/_captions-settings.scss#L45

Should probably be this instead, but I'm not really familiar with the project
```scss
.vjs-caption-settings .vjs-tracksetting {
    label, legend {
        display: block;
        width: 100px;
        margin-bottom: 5px; 
    }
}

```
