### ISSUE TITLE
hide default loading bar

### ISSUE THREAD

**Issue by uikoo9** [videojs/video.js#3585]
I used the picture to customize the loading bar, and want to hide the default loading bar, how to do ?

**Comment by misteroneill** [comment]
Do you mean the video progress control that appears in the control bar?

If so, you can remove it with a function call like `player.removeChild('ProgressControl')` before adding your own progress control.

**Comment by uikoo9** [comment]
thanks,i tried, failed,

![qq 20160830075223](https://cloud.githubusercontent.com/assets/10345351/18071279/270a3a84-6e87-11e6-9f99-aa194860300a.png)

i want to hide this:
![qq 20160830075015](https://cloud.githubusercontent.com/assets/10345351/18071290/371a1bb0-6e87-11e6-9e93-99e51cc99f41.png)

**Comment by misteroneill** [comment]
Ah, the spinner. You could use this CSS, which has to come after video.js' CSS:

```css
.vjs-seeking .vjs-loading-spinner,
.vjs-waiting .vjs-loading-spinner {
  display: none;
}
```
