### ISSUE TITLE
The fluid mode seems has some problems on Firefox and IE.   

### ISSUE THREAD

**Issue by AlexLi88** [videojs/video.js#3871]
## Description
On this http://videojs.com/advanced/ page, the vertical padding seems not correct on Firefox and IE. 
![image](https://cloud.githubusercontent.com/assets/7864399/21274001/f853e03e-c37a-11e6-9ea7-ee0d3b6c86fb.png)

**Comment by gkatsev** [comment]
Thanks, yeah, firefox and IE are a bit weird, not sure what exactly is happening there.

**Comment by Chinese1904** [comment]
I have a similar issue/question.

Firefox 51:
<img width="760" alt="screen shot 2017-02-16 at 8 34 10 pm" src="https://cloud.githubusercontent.com/assets/6228425/23052692/218ee6f4-f488-11e6-8d0e-23c04955b594.png">

Safari 10.0.3 and Chrome 55:
<img width="745" alt="screen shot 2017-02-16 at 8 34 29 pm" src="https://cloud.githubusercontent.com/assets/6228425/23052693/218f3c30-f488-11e6-85ef-ed7bb1626667.png">

This seems to be like an issue for Firefox environments. I am not sure if these two issues correlate?

CC: @gkatsev

**Comment by michabbb** [comment]
btw.. i was forced to override the css to make fluid working in FF:

```css
@-moz-document url-prefix() {
        .video-js.vjs-fluid,
        .video-js.vjs-16-9,
        .video-js.vjs-4-3 {
               width: 100%;
               max-width: 100%;
               height: 100%; 
       }
}
```
i had to set `height: 100%`

don´t know if there is a better way to handle this....
