### ISSUE TITLE
Dynamically set custom primary color

### ISSUE THREAD

**Issue by turshija** [videojs/video.js#4846]
I'm trying to make a video player that can be styled by user dynamically.
Is there any way of passing custom hex for primary color in VideoJS in any way that is not via SCSS directly ?

**Comment by misteroneill** [comment]
There isn't.

In this case, I'd recommend taking advantage of CSS specificity by referring to the specificity of the selector(s) in the default skin and overriding them with your own CSS.

If you need to do this dynamically - such as, by user input - you can [write to your own custom stylesheet via the DOM API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information).

**Comment by gkatsev** [comment]
As @misteroneill said, it isn't supported. However, there are only 3 main classes to target that have a background that you probably want to change, the big play button, the control bar, and the modal dialog. Here's an example of CSS to make the background for everything red:
```css
.video-js .vjs-control-bar, 
.video-js .vjs-big-play-button, 
.video-js .vjs-modal-dialog {
  background-color: red;
}
```

Hope that helps.
