### ISSUE TITLE
Setting the position of closed captions

### ISSUE THREAD

**Issue by JulsRicketti** [videojs/video.js#5004]
## Description
The closed captions I am working with suddenly became larger and changed positions compared to some time before. I have already found how to change the font-size for them, but as it is right now I can't figure out how to change their position.

Here is the current CSS code I have:

```
.video-js .vjs-text-track-display {
/*None of this seems to make a difference.*/
  text-align: center;
  position: absolute;
  bottom: 4em;
  left: 1em;
  right: 1em;
}

/* Had to do this to make the font-size smaller since it was by default way too big*/
::cue {
  font-size: 0.7em;
}
```

## Steps to reproduce

1. Open video
2. Turn on closed captions

### Expected
Would like the closed captions to be nicely positioned on the bottom of the screen.

### Actual
Captions are just floating around the screen, at times in inconvenient positions.

Here are a couple screenshots which show how the closed captions can change their positions and sometimes in inconvenient spots:

![screen shot 2018-03-08 at 1 55 51 pm](https://user-images.githubusercontent.com/886808/37170359-a0f4268c-22d8-11e8-9df4-6b6cf8b81a67.png)
![screen shot 2018-03-08 at 1 56 15 pm](https://user-images.githubusercontent.com/886808/37170360-a123da94-22d8-11e8-8804-d7bb58bf0ff5.png)

**Comment by shivarambodumalla** [comment]
What did you do to change the position

**Comment by hmtri1011** [comment]
Hi @JulsRicketti , how could you change the position, can you share it?

**Comment by JulsRicketti** [comment]
@shivarambodumalla and @hmtri1011 I did it through CSS. Not sure if it has to do with other modifications to the library, but this is what the styles look like when it comes down changing styles and position of the Text Track styles:

```css
/* Text Track Styles */
/* Overall track holder for both captions and subtitles */
.video-js .vjs-text-track-display {
  text-align: center;
  position: absolute;
  bottom: 4em;
  /* Leave padding on left and right *///
  left: 1em;
  right: 1em;
}

/* Move captions down when controls aren't being shown */
.video-js.vjs-user-inactive.vjs-playing .vjs-text-track-display {
  bottom: 1em;
}

/* Individual tracks */
.video-js .vjs-text-track {
  display: none;
  font-size: 1.4em;
  text-align: center;
  margin-bottom: 0.1em;
  /* Transparent black background, or fallback to all black (oldIE) *///
  .background-color-with-alpha(rgb(0, 0, 0), 0.5);
}
```
