### ISSUE TITLE
How to control play/pause use big play button? 

### ISSUE THREAD

**Issue by ShmilyLin** [videojs/video.js#5115]
I hide play button which in control bar, and I want to control play/pause by big play button. 

```css
.vjs-matrix .vjs-playing {
    display: none !important;
}

.vjs-matrix .vjs-paused {
    display: none !important;
}

.vjs-matrix .vjs-current-time {
    display: block !important;
}

.vjs-matrix .vjs-volume-panel {
    display: none !important;
}

.vjs-paused.vjs-has-started .vjs-big-play-button {
    display: block !important;
}

.vjs-playing.vjs-user-active .vjs-big-play-button {
    display: block !important;
}

.vjs-tech {
    pointer-events: none;
}
```

```js
var myPlayer = videojs('h5-video-player', null, function onPlayerReady() {
    var temlPlayer = this;

    this.on('mousemove', function(){
        this.userActive(true);
    });

    this.on('play', function() {
        this.bigPlayButton.show();
    })

    this.on('tap', function(){
        if (this.userActive() === true) {
            this.userActive(false);
        } else {
            this.userActive(true);
        }
    });

    this.on('ended', function() {
        this.hasStarted(false);
        this.exitFullscreen();
    });

    this.bigPlayButton.on('click', function(e) {
        console.log("click", temlPlayer.playbackRate(), temlPlayer.paused());
        // this console.log always is `click 1 false`, I can't judge whether it is playing
        // how can i do?
    })
});
```

I can't get play status in click handle, so what should I do to play/pause player only use big play button?
