### ISSUE TITLE
How keep controls visible before video starting?

### ISSUE THREAD

**Issue by LeoLuanElezi** [videojs/video.js#5143]
How i can do that? is posible with CSS?

**Comment by gkatsev** [comment]
Are you trying to show the control bar in addition to the big play button?

**Comment by gkatsev** [comment]
You can try adding `vjs-has-started` class, but that will hide the big play button and the poster.

something like:
```css
:not(.vjs-has-started) .vjs-control-bar {
  display: flex;
}
```
might be a better idea.
