### ISSUE TITLE
Hide Time Tooltip (need help)

### ISSUE THREAD

**Issue by coddok** [videojs/video.js#5410]
There are any chance to hide time-tooltip but keep mouse-display only through css?
Like  [this](https://i.imgur.com/rpyZBfG.png)
I got this effect by manually deleting <div class="vjs-time-tooltip"...> under <div class="vjs-play-progress vjs-slider-bar"...>. Of cource, it's appears again after page is reloaded.

**Comment by coddok** [comment]
Forget to say. Video.js 7.1.0

**Comment by alex-barstow** [comment]
The easiest way to hide it is via options when you initialize the player:

```js
var player = videojs('my_video_1', {
  controlBar: {
    progressControl: {
      seekBar: {
        playProgressBar: false
      }
    }
  }
});
```

See a working example [here](http://jsbin.com/deliziyami/1/edit?html,output). Doing it this way will also make sure that component remains hidden between page loads.

**Comment by alex-barstow** [comment]
You can hide it by adding the following CSS after the default video.js styles have loaded:

```css
.video-js .vjs-progress-control:hover .vjs-play-progress:after {
  display: none;
}
```

Hope this helps!

**Comment by alecsgone** [comment]
Minor tweak for v7 to hide `<div class="vjs-time-tooltip"...>` only with css is 
```css
.video-js .vjs-progress-control:hover .vjs-play-progress .vjs-time-tooltip {
  display: none;
}
```

**Comment by gkatsev** [comment]
a simple css would just be
```css
.vjs-time-tooltip {
  display: none !important;
}
```

I think there may be an option to turn it off but I'm not sure, let me check.

**Comment by gkatsev** [comment]
Oh, I misread the specific want.
The simplest CSS would just be
```css
.vjs-play-progress .vjs-time-tooltip {
  display: none !important;
}
```

It's fine to use `!important` here because you're overriding a style, plus, it makes sure that if the selector that Video.js uses changes for whatever reason, the tooltip stays hidden.
