### ISSUE TITLE
An overwrite conflict occurs when a page introduces another font file. 

### ISSUE THREAD

**Issue by jsperorg** [videojs/video.js#6377]
## Description & Solution

I introduced VideoJs and other font files on one page. But the other fonts overwrite VideoJs fonts, and the ICONS specified in video-js.css are not the ICONS for VideoJs fonts. You need to add: 
`font-family: VideoJS;`
in to the first block of CSS code of video-js.css. like this:
```css

.vjs-modal-dialog .vjs-modal-dialog-content, .video-js .vjs-modal-dialog, .vjs-button > .vjs-icon-placeholder:before, .video-js .vjs-big-play-button .vjs-icon-placeholder:before {
  font-family: VideoJS;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

**Comment by gkatsev** [comment]
Do you have an example of what you mean? Looking at the code generated code, I see that both the big-play-button gets set up properly with `font-family: VideoJS` a bit further down in the CSS:
```css
.vjs-icon-play, .video-js .vjs-play-control .vjs-icon-placeholder, .video-js .vjs-big-play-button .vjs-icon-placeholder:before {
  font-family: VideoJS;
  font-weight: normal;
  font-style: normal;
}
```
So, it seems like everything should be fine.
