### ISSUE TITLE
all dependencies need to be explicit for yarn 2

### ISSUE THREAD

**Issue by yurique** [videojs/video.js#7109]
## Description

When using yarn 2, the build fails with a number errors like the following:
```
ERROR in ./.yarn/cache/video.js-npm-7.11.5-3be776ec17-e014baaa89.zip/node_modules/video.js/dist/video.es.js 27:0-37
Module not found: Error: Can't resolve 'm3u8-parser' in '/ ... /.yarn/cache/video.js-npm-7.11.5-3be776ec17-e014baaa89.zip/node_modules/video.js/dist'
```

I believe the reason for that is that some dependencies are not explicit and come transitively from `@videojs/http-streaming`.

The workaround is to add those dependencies to the `.yarnrc.yml`:

```yaml
yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "video.js@7.11.5":
    dependencies:
      "mux.js": "*"
      "@videojs/vhs-utils": "2.3.0"
      "m3u8-parser": "4.5.0"
      "mpd-parser": "0.15.0"
```

What makes it more cumbersome is that we need to pin down those versions (otherwise yarn will resolve vhs-utils v3 which is not compatible with video.js 7.11.5).

The solution for this would be listing these dependencies explicitly in `package.json`.

#### videojs
7.11.5
