### ISSUE TITLE
how to make preview and play button on buttom left (which is best practise)

### ISSUE THREAD

**Issue by kosuodhmwa** [videojs/video.js#7324]
Hi there

As the title says:

![video_js](https://user-images.githubusercontent.com/24782840/125992880-5a47ecb2-2f38-45ee-a6df-5892ced10547.JPG)

The video works, but the way how it will be display is a lil bit string i.m.o...

thx for feedback.

**Comment by gkatsev** [comment]
You can use css that targets `vjs-big-play-button`. For example:

```css
.video-js .vjs-big-play-button {
    bottom: 1em;
    left: 1em;
    top: unset;
}
```
