### ISSUE TITLE
Video maximum height rule is not enforced for fluid mode

### ISSUE THREAD

**Issue by pavlexander** [videojs/video.js#7612]
## Description
`Fluid` mode, while allowing the height to auto-adjust - completely ignores the `maximum height`, therefore making the video non-responsive to viewport size changes.

## Steps to reproduce
1. Set the `fluid: true` flag, enforce `max-height: 60vh` rule.
2. Try resizing the viewport - `max-height` rule is ignored when viewport size is `<60vh`

### Expected
Video is scaled down

![image](https://user-images.githubusercontent.com/20644772/149740933-312d7b9d-4448-453d-b605-cc4319f8b82b.png)

### Actual
Video remains in original height

![image](https://user-images.githubusercontent.com/20644772/149740396-bf768478-262a-4675-b636-3868144628c3.png)

#### videojs
 7.17.0
#### browsers
all (Chrome, Opera)
#### OSes
Win 10 (all?)

## Code to reproduce

```html
<div class="container-fluid">
  <div class="row g-1">
    <div class="col-6 text-center">
      <h3>Video</h3>
    </div>
    <div class="col-6 text-center">
      <h3>Image</h3>
    </div>
  </div>
  <div class="row g-1">
    <div class="col-6">
      <div id="carouselExampleControls" class="carousel" data-bs-interval="false">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <video id="my_video_1" class="video-js vjs-default-skin vjs-big-play-centered vjs-show-big-play-button-on-pause carouselitemmedia" controls preload="auto" data-setup='{ "fluid": true  }'>
              <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
            </video>
          </div>
          <div class="carousel-item">
            <img src="https://dummyimage.com/960x400/000/fff." class="carouselitemmedia">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="col-6">
      <div id="carouselExampleControls2" class="carousel" data-bs-interval="false">
        <div class="carousel-inner">
          <div class="carousel-item">
            <video id="my_video_1" class="video-js vjs-default-skin vjs-big-play-centered vjs-show-big-play-button-on-pause carouselitemmedia" controls preload="auto" data-setup='{ "fluid": false, "fill": false  }'>
              <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
            </video>
          </div>
          <div class="carousel-item active">
            <img src="https://dummyimage.com/960x400/000/fff." class="carouselitemmedia">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls2" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls2" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>
</div>
```

```css
body: {
  height: 100%;
  width: 100%;
}

#column {
  height: 100vh;
  width: 40vw;
  background-color: grey;
}

.carousel {
  width: 100%;
  background-color: red;
}

.carousel-item {
  text-align: center;
}

.carouselitemmedia {
  max-width: 100%;
  max-height: 60vh;
}

.video-js {
  background: content-box;
}
```
Fiddle: http://jsfiddle.net/w5v7f6ut/1/

When `vh > 60` (OK)

![image](https://user-images.githubusercontent.com/20644772/149740292-884d5569-5733-4224-a6dd-f6252f5542fd.png)

I can manage to achieve the expected result by disabling the fluidicity (`fluid: false`), but then when the `vh > 60` - video is no longer fitting the content size:

![image](https://user-images.githubusercontent.com/20644772/149741477-478c8be2-0a65-4cac-93aa-9b774021a936.png)

If the result is expected - could you tell if it's possible to achieve a mix of `fit-fluid` mode somehow?

**Comment by mister-ben** [comment]
Fluid uses 100% width and 0 height, and padding to maintain the aspect ratio. max-height will have no effect as the height is already 0. Fit is 100% width and height. You're probably best with styles on the player's parent element to set its height and using fill on the player.

**Comment by pavlexander** [comment]
@mister-ben thank you. I was digging in the wrong direction. With your advice I was able to solve the problem (by randomly applying styles) :)

Here is the result:

https://user-images.githubusercontent.com/20644772/149791791-ae758d8d-9d43-4b7c-badf-236efc3c64eb.mp4

In case if/when video is removed here is the fiddle: http://jsfiddle.net/26xuf47j/1/

styles:

```css
body: {
  height: 100%;
  width: 100%;
}

#column {
  height: 100vh;
  width: 40vw;
  background-color: grey;
}

.carousel {
  background-color: red;

  width: 100%;
  height: 100%;
  max-height: 60vh;
}

.carousel-inner {
  width: 100%;
  height: 100%;
}

.carousel-item {
  text-align: center;

  width: 100%;
  height: 100%;
  max-width: 100%;
}

img {
  max-width: 100%;
  max-height: 100%;
}

.video-js {
  background: content-box;
  position: static;
  height: auto;
}
```

are there any consequences that I need to be aware of when using `static` display type on `videojs`? It looks like the solution is working for now. I will close the ticket in the following days. Want to make sure that everything is done correctly so if anybody has any improvement suggestions your are welcomed. Would be nice if this kind of functionality would be built into `videojs` or documented somewhere..

**Comment by pavlexander** [comment]
got to say that the need to specify 100 height in every single parent really messes up with my more complex layout.. Hack on top of hack to make UI responsive.

**Comment by mister-ben** [comment]
If you don't need to care about internet explorer and can use `aspect-ratio`, then this would work.

```css
.video-js {
  height: auto;
  aspect-ratio: 96/40;
}
```

Otherwise aspect ratio has always been a hack in CSS. We could probably make the built in fluid mode work with this in future but it's a breaking change.
