### ISSUE TITLE
 The bar is not centered in video control section

### ISSUE THREAD

**Issue by KangXinzhi** [videojs/video.js#7989]
### Description

<img width="546" alt="image" src="https://user-images.githubusercontent.com/50164727/199654693-acde1ac4-2a77-40a0-a572-a1b3fc761f48.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/50164727/199654592-525ba725-d905-4a66-a9b8-549c6c444e0e.png">

### Steps to reproduce

1.
2.
3.

### What version of Video.js are you using?

^7.20.3

### What browser(s) including version(s) does this occur with?

chrome 104.0.5112.81

### What OS(es) and version(s) does this occur with?

mac

**Comment by KangXinzhi** [comment]
i try fixed
<img width="622" alt="image" src="https://user-images.githubusercontent.com/50164727/199654831-f93034e2-e285-4a7b-8c3d-83dee2e5acb6.png">

hover：
<img width="679" alt="image" src="https://user-images.githubusercontent.com/50164727/199654892-d553d019-9e4d-41e7-8588-b755b0bb64de.png">

**Comment by mister-ben** [comment]
Fixed in #7990, which will be in the next v8.x release.

CSS like below could be used for v7.x players.

```css
    .video-js .vjs-volume-level:before,
    .video-js .vjs-play-progress:before {
      top: unset !important;
      line-height: .35em;
    }
```
