### ISSUE TITLE
How to show TitleBar permanently

### ISSUE THREAD

**Issue by RithiSethTes** [videojs/video.js#8139]
### Description

I want to show the new TitleBar permanently even when the user is inactive, except when the player is ended.
Is there any options?

![vjstitlebar](https://i.imgur.com/6p3U6vm.png)

### Steps to reproduce

1.
2.
3.

### Errors

No error.

### What version of Video.js are you using?

8.0.4

### Video.js plugins used.

No

### What browser(s) including version(s) does this occur with?

Google Chrome Version 110

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by mister-ben** [comment]
```css
.video-js.vjs-playing.vjs-user-inactive .vjs-title-bar {
  opacity: 1;
}
```

Or replace `.video-js` with a class you add to the player.
