### ISSUE TITLE
How to change TitleBar font?

### ISSUE THREAD

**Issue by friendtasy** [videojs/video.js#8140]
### Description

How to change TitleBar font size?

### Steps to reproduce

1.
2.
3.

### What version of Video.js are you using?

8.0.4

### What browser(s) including version(s) does this occur with?

chrome 110

### What OS(es) and version(s) does this occur with?

win11

**Comment by mister-ben** [comment]
```css
.vjs-title-bar {
  font-family: "Comic Sans MS", "Comic Sans", cursive;
}
```
