### ISSUE TITLE
.vjs-big-play-button vertically off-center

### ISSUE THREAD

**Issue by reggiedotre** [videojs/video.js#8411]
The line-height property should be the same as height to center the play button.

https://github.com/videojs/video.js/blob/b95cd7a6eb994f584bfdb23b7769bc86445c41f5/src/css/components/_big-play.scss#L5-L6

The way it is now:
![image](https://github.com/videojs/video.js/assets/129338753/5ce889aa-e365-4530-b90f-4b288e816444)

After changing height to match line-height:
![image](https://github.com/videojs/video.js/assets/129338753/2ea9f905-6512-41f2-a82c-b5cb2cfe7733)

As you can see the first one is slightly off-center, while the second one is ok.

I want to mention that I have only changed the sizes manually in the .css file (both to 1.5em) and haven't actually tried changing the linked .scss file so I do not know if changing it has any implications.

**Comment by amtins** [comment]
@reggiedotre thanks for the issue. I've created a [PR](https://github.com/videojs/video.js/pull/8398) to make it easier to customize the big-play-button. However, my proposal has a high risk of breaking a lot of integration based on current css rules, following discussions I had with @mister-ben  and @misteroneill.

That's why I'm going to close it in the next few days and include it in another PR to try and offer a new development experience for player customization in the next few weeks or months (?).

In the meantime, you can do the following:

```css
        .video-js .vjs-big-play-button {
            line-height: inherit;
            /* height: 3em; */ /* you can set a new height */

            margin-top: unset;
            margin-left: unset;
            transform: translate(-50%, -50%); 
        }
        .video-js .vjs-big-play-button .vjs-icon-placeholder::before {
            position: inherit;
            top: unset;
            left: unset;
            display: flex;
            justify-content: center;
            align-items: center;
        }
```
